// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v6.32.0
// source: macros.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { BehaviorBinding } from "./keymap";

export const protobufPackage = "zmk.macros";

export enum SetMacroDetailsResponse {
  SET_MACRO_DETAILS_RESP_OK = 0,
  SET_MACRO_DETAILS_RESP_ERR_GENERIC = 1,
  SET_MACRO_DETAILS_RESP_ERR_INVALID_INDEX = 2,
  SET_MACRO_DETAILS_RESP_ERR_TOO_MANY_STEPS = 3,
  UNRECOGNIZED = -1,
}

export function setMacroDetailsResponseFromJSON(object: any): SetMacroDetailsResponse {
  switch (object) {
    case 0:
    case "SET_MACRO_DETAILS_RESP_OK":
      return SetMacroDetailsResponse.SET_MACRO_DETAILS_RESP_OK;
    case 1:
    case "SET_MACRO_DETAILS_RESP_ERR_GENERIC":
      return SetMacroDetailsResponse.SET_MACRO_DETAILS_RESP_ERR_GENERIC;
    case 2:
    case "SET_MACRO_DETAILS_RESP_ERR_INVALID_INDEX":
      return SetMacroDetailsResponse.SET_MACRO_DETAILS_RESP_ERR_INVALID_INDEX;
    case 3:
    case "SET_MACRO_DETAILS_RESP_ERR_TOO_MANY_STEPS":
      return SetMacroDetailsResponse.SET_MACRO_DETAILS_RESP_ERR_TOO_MANY_STEPS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SetMacroDetailsResponse.UNRECOGNIZED;
  }
}

export function setMacroDetailsResponseToJSON(object: SetMacroDetailsResponse): string {
  switch (object) {
    case SetMacroDetailsResponse.SET_MACRO_DETAILS_RESP_OK:
      return "SET_MACRO_DETAILS_RESP_OK";
    case SetMacroDetailsResponse.SET_MACRO_DETAILS_RESP_ERR_GENERIC:
      return "SET_MACRO_DETAILS_RESP_ERR_GENERIC";
    case SetMacroDetailsResponse.SET_MACRO_DETAILS_RESP_ERR_INVALID_INDEX:
      return "SET_MACRO_DETAILS_RESP_ERR_INVALID_INDEX";
    case SetMacroDetailsResponse.SET_MACRO_DETAILS_RESP_ERR_TOO_MANY_STEPS:
      return "SET_MACRO_DETAILS_RESP_ERR_TOO_MANY_STEPS";
    case SetMacroDetailsResponse.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Request {
  getMacroList?: boolean | undefined;
  getMacroDetails?: number | undefined;
  setMacroDetails?: SetMacroDetailsRequest | undefined;
}

export interface Response {
  getMacroList?: MacroList | undefined;
  getMacroDetails?: MacroDetails | undefined;
  setMacroDetails?: SetMacroDetailsResponse | undefined;
}

export interface MacroList {
  macros: MacroInfo[];
}

export interface MacroInfo {
  index: number;
  maxSteps: number;
}

export interface MacroDetails {
  index: number;
  bindings: BehaviorBinding[];
}

export interface SetMacroDetailsRequest {
  index: number;
  bindings: BehaviorBinding[];
}

export interface Notification {
}

function createBaseRequest(): Request {
  return { getMacroList: undefined, getMacroDetails: undefined, setMacroDetails: undefined };
}

export const Request = {
  encode(message: Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.getMacroList !== undefined) {
      writer.uint32(8).bool(message.getMacroList);
    }
    if (message.getMacroDetails !== undefined) {
      writer.uint32(16).uint32(message.getMacroDetails);
    }
    if (message.setMacroDetails !== undefined) {
      SetMacroDetailsRequest.encode(message.setMacroDetails, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.getMacroList = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.getMacroDetails = reader.uint32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.setMacroDetails = SetMacroDetailsRequest.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Request {
    return {
      getMacroList: isSet(object.getMacroList) ? globalThis.Boolean(object.getMacroList) : undefined,
      getMacroDetails: isSet(object.getMacroDetails) ? globalThis.Number(object.getMacroDetails) : undefined,
      setMacroDetails: isSet(object.setMacroDetails)
        ? SetMacroDetailsRequest.fromJSON(object.setMacroDetails)
        : undefined,
    };
  },

  toJSON(message: Request): unknown {
    const obj: any = {};
    if (message.getMacroList !== undefined) {
      obj.getMacroList = message.getMacroList;
    }
    if (message.getMacroDetails !== undefined) {
      obj.getMacroDetails = Math.round(message.getMacroDetails);
    }
    if (message.setMacroDetails !== undefined) {
      obj.setMacroDetails = SetMacroDetailsRequest.toJSON(message.setMacroDetails);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Request>, I>>(base?: I): Request {
    return Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request>, I>>(object: I): Request {
    const message = createBaseRequest();
    message.getMacroList = object.getMacroList ?? undefined;
    message.getMacroDetails = object.getMacroDetails ?? undefined;
    message.setMacroDetails = (object.setMacroDetails !== undefined && object.setMacroDetails !== null)
      ? SetMacroDetailsRequest.fromPartial(object.setMacroDetails)
      : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return { getMacroList: undefined, getMacroDetails: undefined, setMacroDetails: undefined };
}

export const Response = {
  encode(message: Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.getMacroList !== undefined) {
      MacroList.encode(message.getMacroList, writer.uint32(10).fork()).ldelim();
    }
    if (message.getMacroDetails !== undefined) {
      MacroDetails.encode(message.getMacroDetails, writer.uint32(18).fork()).ldelim();
    }
    if (message.setMacroDetails !== undefined) {
      writer.uint32(24).int32(message.setMacroDetails);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.getMacroList = MacroList.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.getMacroDetails = MacroDetails.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.setMacroDetails = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return {
      getMacroList: isSet(object.getMacroList) ? MacroList.fromJSON(object.getMacroList) : undefined,
      getMacroDetails: isSet(object.getMacroDetails) ? MacroDetails.fromJSON(object.getMacroDetails) : undefined,
      setMacroDetails: isSet(object.setMacroDetails)
        ? setMacroDetailsResponseFromJSON(object.setMacroDetails)
        : undefined,
    };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.getMacroList !== undefined) {
      obj.getMacroList = MacroList.toJSON(message.getMacroList);
    }
    if (message.getMacroDetails !== undefined) {
      obj.getMacroDetails = MacroDetails.toJSON(message.getMacroDetails);
    }
    if (message.setMacroDetails !== undefined) {
      obj.setMacroDetails = setMacroDetailsResponseToJSON(message.setMacroDetails);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Response>, I>>(base?: I): Response {
    return Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Response>, I>>(object: I): Response {
    const message = createBaseResponse();
    message.getMacroList = (object.getMacroList !== undefined && object.getMacroList !== null)
      ? MacroList.fromPartial(object.getMacroList)
      : undefined;
    message.getMacroDetails = (object.getMacroDetails !== undefined && object.getMacroDetails !== null)
      ? MacroDetails.fromPartial(object.getMacroDetails)
      : undefined;
    message.setMacroDetails = object.setMacroDetails ?? undefined;
    return message;
  },
};

function createBaseMacroList(): MacroList {
  return { macros: [] };
}

export const MacroList = {
  encode(message: MacroList, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.macros) {
      MacroInfo.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MacroList {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMacroList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.macros.push(MacroInfo.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MacroList {
    return {
      macros: globalThis.Array.isArray(object?.macros) ? object.macros.map((e: any) => MacroInfo.fromJSON(e)) : [],
    };
  },

  toJSON(message: MacroList): unknown {
    const obj: any = {};
    if (message.macros?.length) {
      obj.macros = message.macros.map((e) => MacroInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MacroList>, I>>(base?: I): MacroList {
    return MacroList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MacroList>, I>>(object: I): MacroList {
    const message = createBaseMacroList();
    message.macros = object.macros?.map((e) => MacroInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMacroInfo(): MacroInfo {
  return { index: 0, maxSteps: 0 };
}

export const MacroInfo = {
  encode(message: MacroInfo, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.index !== 0) {
      writer.uint32(8).uint32(message.index);
    }
    if (message.maxSteps !== 0) {
      writer.uint32(16).uint32(message.maxSteps);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MacroInfo {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMacroInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.index = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.maxSteps = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MacroInfo {
    return {
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      maxSteps: isSet(object.maxSteps) ? globalThis.Number(object.maxSteps) : 0,
    };
  },

  toJSON(message: MacroInfo): unknown {
    const obj: any = {};
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.maxSteps !== 0) {
      obj.maxSteps = Math.round(message.maxSteps);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MacroInfo>, I>>(base?: I): MacroInfo {
    return MacroInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MacroInfo>, I>>(object: I): MacroInfo {
    const message = createBaseMacroInfo();
    message.index = object.index ?? 0;
    message.maxSteps = object.maxSteps ?? 0;
    return message;
  },
};

function createBaseMacroDetails(): MacroDetails {
  return { index: 0, bindings: [] };
}

export const MacroDetails = {
  encode(message: MacroDetails, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.index !== 0) {
      writer.uint32(8).uint32(message.index);
    }
    for (const v of message.bindings) {
      BehaviorBinding.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MacroDetails {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMacroDetails();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.index = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.bindings.push(BehaviorBinding.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MacroDetails {
    return {
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      bindings: globalThis.Array.isArray(object?.bindings)
        ? object.bindings.map((e: any) => BehaviorBinding.fromJSON(e))
        : [],
    };
  },

  toJSON(message: MacroDetails): unknown {
    const obj: any = {};
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.bindings?.length) {
      obj.bindings = message.bindings.map((e) => BehaviorBinding.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MacroDetails>, I>>(base?: I): MacroDetails {
    return MacroDetails.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MacroDetails>, I>>(object: I): MacroDetails {
    const message = createBaseMacroDetails();
    message.index = object.index ?? 0;
    message.bindings = object.bindings?.map((e) => BehaviorBinding.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSetMacroDetailsRequest(): SetMacroDetailsRequest {
  return { index: 0, bindings: [] };
}

export const SetMacroDetailsRequest = {
  encode(message: SetMacroDetailsRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.index !== 0) {
      writer.uint32(8).uint32(message.index);
    }
    for (const v of message.bindings) {
      BehaviorBinding.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetMacroDetailsRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetMacroDetailsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.index = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.bindings.push(BehaviorBinding.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetMacroDetailsRequest {
    return {
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      bindings: globalThis.Array.isArray(object?.bindings)
        ? object.bindings.map((e: any) => BehaviorBinding.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SetMacroDetailsRequest): unknown {
    const obj: any = {};
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.bindings?.length) {
      obj.bindings = message.bindings.map((e) => BehaviorBinding.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetMacroDetailsRequest>, I>>(base?: I): SetMacroDetailsRequest {
    return SetMacroDetailsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetMacroDetailsRequest>, I>>(object: I): SetMacroDetailsRequest {
    const message = createBaseSetMacroDetailsRequest();
    message.index = object.index ?? 0;
    message.bindings = object.bindings?.map((e) => BehaviorBinding.fromPartial(e)) || [];
    return message;
  },
};

function createBaseNotification(): Notification {
  return {};
}

export const Notification = {
  encode(_: Notification, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Notification {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Notification {
    return {};
  },

  toJSON(_: Notification): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Notification>, I>>(base?: I): Notification {
    return Notification.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Notification>, I>>(_: I): Notification {
    const message = createBaseNotification();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
