// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v6.32.0
// source: sensors.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export const protobufPackage = "zmk.sensors";

export enum SetSensorDetailsResponse {
  SET_SENSOR_DETAILS_RESP_OK = 0,
  SET_SENSOR_DETAILS_RESP_INVALID_SENSOR = 1,
  SET_SENSOR_DETAILS_RESP_INVALID_LAYER = 2,
  SET_SENSOR_DETAILS_RESP_INVALID_BEHAVIOR = 3,
  SET_SENSOR_DETAILS_RESP_INVALID_PARAMETERS = 4,
  UNRECOGNIZED = -1,
}

export function setSensorDetailsResponseFromJSON(object: any): SetSensorDetailsResponse {
  switch (object) {
    case 0:
    case "SET_SENSOR_DETAILS_RESP_OK":
      return SetSensorDetailsResponse.SET_SENSOR_DETAILS_RESP_OK;
    case 1:
    case "SET_SENSOR_DETAILS_RESP_INVALID_SENSOR":
      return SetSensorDetailsResponse.SET_SENSOR_DETAILS_RESP_INVALID_SENSOR;
    case 2:
    case "SET_SENSOR_DETAILS_RESP_INVALID_LAYER":
      return SetSensorDetailsResponse.SET_SENSOR_DETAILS_RESP_INVALID_LAYER;
    case 3:
    case "SET_SENSOR_DETAILS_RESP_INVALID_BEHAVIOR":
      return SetSensorDetailsResponse.SET_SENSOR_DETAILS_RESP_INVALID_BEHAVIOR;
    case 4:
    case "SET_SENSOR_DETAILS_RESP_INVALID_PARAMETERS":
      return SetSensorDetailsResponse.SET_SENSOR_DETAILS_RESP_INVALID_PARAMETERS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SetSensorDetailsResponse.UNRECOGNIZED;
  }
}

export function setSensorDetailsResponseToJSON(object: SetSensorDetailsResponse): string {
  switch (object) {
    case SetSensorDetailsResponse.SET_SENSOR_DETAILS_RESP_OK:
      return "SET_SENSOR_DETAILS_RESP_OK";
    case SetSensorDetailsResponse.SET_SENSOR_DETAILS_RESP_INVALID_SENSOR:
      return "SET_SENSOR_DETAILS_RESP_INVALID_SENSOR";
    case SetSensorDetailsResponse.SET_SENSOR_DETAILS_RESP_INVALID_LAYER:
      return "SET_SENSOR_DETAILS_RESP_INVALID_LAYER";
    case SetSensorDetailsResponse.SET_SENSOR_DETAILS_RESP_INVALID_BEHAVIOR:
      return "SET_SENSOR_DETAILS_RESP_INVALID_BEHAVIOR";
    case SetSensorDetailsResponse.SET_SENSOR_DETAILS_RESP_INVALID_PARAMETERS:
      return "SET_SENSOR_DETAILS_RESP_INVALID_PARAMETERS";
    case SetSensorDetailsResponse.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Request {
  listAllSensors?: boolean | undefined;
  getSensorDetails?: GetSensorDetailsRequest | undefined;
  setSensorDetails?: SetSensorDetailsRequest | undefined;
}

export interface GetSensorDetailsRequest {
  sensorId: number;
}

export interface Response {
  listAllSensors?: ListAllSensorsResponse | undefined;
  getSensorDetails?: GetSensorDetailsResponse | undefined;
  setSensorDetails?: SetSensorDetailsResponse | undefined;
}

export interface ListAllSensorsResponse {
  sensors: number[];
}

export interface SetSensorDetailsRequest {
  sensorId: number;
  layerId: number;
  bindings: BehaviorBinding[];
}

export interface GetSensorDetailsResponse {
  sensorId: number;
  displayName: string;
  layers: Layer[];
}

export interface Layer {
  id: number;
  name: string;
  bindings: BehaviorBinding[];
}

export interface BehaviorBinding {
  behaviorId: number;
  param1: number;
  param2: number;
}

export interface Notification {
  unsavedChangesStatusChanged?: boolean | undefined;
}

function createBaseRequest(): Request {
  return { listAllSensors: undefined, getSensorDetails: undefined, setSensorDetails: undefined };
}

export const Request = {
  encode(message: Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.listAllSensors !== undefined) {
      writer.uint32(8).bool(message.listAllSensors);
    }
    if (message.getSensorDetails !== undefined) {
      GetSensorDetailsRequest.encode(message.getSensorDetails, writer.uint32(18).fork()).ldelim();
    }
    if (message.setSensorDetails !== undefined) {
      SetSensorDetailsRequest.encode(message.setSensorDetails, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.listAllSensors = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.getSensorDetails = GetSensorDetailsRequest.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.setSensorDetails = SetSensorDetailsRequest.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Request {
    return {
      listAllSensors: isSet(object.listAllSensors) ? globalThis.Boolean(object.listAllSensors) : undefined,
      getSensorDetails: isSet(object.getSensorDetails)
        ? GetSensorDetailsRequest.fromJSON(object.getSensorDetails)
        : undefined,
      setSensorDetails: isSet(object.setSensorDetails)
        ? SetSensorDetailsRequest.fromJSON(object.setSensorDetails)
        : undefined,
    };
  },

  toJSON(message: Request): unknown {
    const obj: any = {};
    if (message.listAllSensors !== undefined) {
      obj.listAllSensors = message.listAllSensors;
    }
    if (message.getSensorDetails !== undefined) {
      obj.getSensorDetails = GetSensorDetailsRequest.toJSON(message.getSensorDetails);
    }
    if (message.setSensorDetails !== undefined) {
      obj.setSensorDetails = SetSensorDetailsRequest.toJSON(message.setSensorDetails);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Request>, I>>(base?: I): Request {
    return Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request>, I>>(object: I): Request {
    const message = createBaseRequest();
    message.listAllSensors = object.listAllSensors ?? undefined;
    message.getSensorDetails = (object.getSensorDetails !== undefined && object.getSensorDetails !== null)
      ? GetSensorDetailsRequest.fromPartial(object.getSensorDetails)
      : undefined;
    message.setSensorDetails = (object.setSensorDetails !== undefined && object.setSensorDetails !== null)
      ? SetSensorDetailsRequest.fromPartial(object.setSensorDetails)
      : undefined;
    return message;
  },
};

function createBaseGetSensorDetailsRequest(): GetSensorDetailsRequest {
  return { sensorId: 0 };
}

export const GetSensorDetailsRequest = {
  encode(message: GetSensorDetailsRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.sensorId !== 0) {
      writer.uint32(8).uint32(message.sensorId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetSensorDetailsRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSensorDetailsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.sensorId = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSensorDetailsRequest {
    return { sensorId: isSet(object.sensorId) ? globalThis.Number(object.sensorId) : 0 };
  },

  toJSON(message: GetSensorDetailsRequest): unknown {
    const obj: any = {};
    if (message.sensorId !== 0) {
      obj.sensorId = Math.round(message.sensorId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetSensorDetailsRequest>, I>>(base?: I): GetSensorDetailsRequest {
    return GetSensorDetailsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetSensorDetailsRequest>, I>>(object: I): GetSensorDetailsRequest {
    const message = createBaseGetSensorDetailsRequest();
    message.sensorId = object.sensorId ?? 0;
    return message;
  },
};

function createBaseResponse(): Response {
  return { listAllSensors: undefined, getSensorDetails: undefined, setSensorDetails: undefined };
}

export const Response = {
  encode(message: Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.listAllSensors !== undefined) {
      ListAllSensorsResponse.encode(message.listAllSensors, writer.uint32(10).fork()).ldelim();
    }
    if (message.getSensorDetails !== undefined) {
      GetSensorDetailsResponse.encode(message.getSensorDetails, writer.uint32(18).fork()).ldelim();
    }
    if (message.setSensorDetails !== undefined) {
      writer.uint32(24).int32(message.setSensorDetails);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.listAllSensors = ListAllSensorsResponse.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.getSensorDetails = GetSensorDetailsResponse.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.setSensorDetails = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return {
      listAllSensors: isSet(object.listAllSensors) ? ListAllSensorsResponse.fromJSON(object.listAllSensors) : undefined,
      getSensorDetails: isSet(object.getSensorDetails)
        ? GetSensorDetailsResponse.fromJSON(object.getSensorDetails)
        : undefined,
      setSensorDetails: isSet(object.setSensorDetails)
        ? setSensorDetailsResponseFromJSON(object.setSensorDetails)
        : undefined,
    };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.listAllSensors !== undefined) {
      obj.listAllSensors = ListAllSensorsResponse.toJSON(message.listAllSensors);
    }
    if (message.getSensorDetails !== undefined) {
      obj.getSensorDetails = GetSensorDetailsResponse.toJSON(message.getSensorDetails);
    }
    if (message.setSensorDetails !== undefined) {
      obj.setSensorDetails = setSensorDetailsResponseToJSON(message.setSensorDetails);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Response>, I>>(base?: I): Response {
    return Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Response>, I>>(object: I): Response {
    const message = createBaseResponse();
    message.listAllSensors = (object.listAllSensors !== undefined && object.listAllSensors !== null)
      ? ListAllSensorsResponse.fromPartial(object.listAllSensors)
      : undefined;
    message.getSensorDetails = (object.getSensorDetails !== undefined && object.getSensorDetails !== null)
      ? GetSensorDetailsResponse.fromPartial(object.getSensorDetails)
      : undefined;
    message.setSensorDetails = object.setSensorDetails ?? undefined;
    return message;
  },
};

function createBaseListAllSensorsResponse(): ListAllSensorsResponse {
  return { sensors: [] };
}

export const ListAllSensorsResponse = {
  encode(message: ListAllSensorsResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    writer.uint32(10).fork();
    for (const v of message.sensors) {
      writer.uint32(v);
    }
    writer.ldelim();
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListAllSensorsResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAllSensorsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag === 8) {
            message.sensors.push(reader.uint32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.sensors.push(reader.uint32());
            }

            continue;
          }

          break;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListAllSensorsResponse {
    return {
      sensors: globalThis.Array.isArray(object?.sensors) ? object.sensors.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: ListAllSensorsResponse): unknown {
    const obj: any = {};
    if (message.sensors?.length) {
      obj.sensors = message.sensors.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListAllSensorsResponse>, I>>(base?: I): ListAllSensorsResponse {
    return ListAllSensorsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListAllSensorsResponse>, I>>(object: I): ListAllSensorsResponse {
    const message = createBaseListAllSensorsResponse();
    message.sensors = object.sensors?.map((e) => e) || [];
    return message;
  },
};

function createBaseSetSensorDetailsRequest(): SetSensorDetailsRequest {
  return { sensorId: 0, layerId: 0, bindings: [] };
}

export const SetSensorDetailsRequest = {
  encode(message: SetSensorDetailsRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.sensorId !== 0) {
      writer.uint32(8).uint32(message.sensorId);
    }
    if (message.layerId !== 0) {
      writer.uint32(16).uint32(message.layerId);
    }
    for (const v of message.bindings) {
      BehaviorBinding.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetSensorDetailsRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetSensorDetailsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.sensorId = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.layerId = reader.uint32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.bindings.push(BehaviorBinding.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetSensorDetailsRequest {
    return {
      sensorId: isSet(object.sensorId) ? globalThis.Number(object.sensorId) : 0,
      layerId: isSet(object.layerId) ? globalThis.Number(object.layerId) : 0,
      bindings: globalThis.Array.isArray(object?.bindings)
        ? object.bindings.map((e: any) => BehaviorBinding.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SetSensorDetailsRequest): unknown {
    const obj: any = {};
    if (message.sensorId !== 0) {
      obj.sensorId = Math.round(message.sensorId);
    }
    if (message.layerId !== 0) {
      obj.layerId = Math.round(message.layerId);
    }
    if (message.bindings?.length) {
      obj.bindings = message.bindings.map((e) => BehaviorBinding.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetSensorDetailsRequest>, I>>(base?: I): SetSensorDetailsRequest {
    return SetSensorDetailsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetSensorDetailsRequest>, I>>(object: I): SetSensorDetailsRequest {
    const message = createBaseSetSensorDetailsRequest();
    message.sensorId = object.sensorId ?? 0;
    message.layerId = object.layerId ?? 0;
    message.bindings = object.bindings?.map((e) => BehaviorBinding.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetSensorDetailsResponse(): GetSensorDetailsResponse {
  return { sensorId: 0, displayName: "", layers: [] };
}

export const GetSensorDetailsResponse = {
  encode(message: GetSensorDetailsResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.sensorId !== 0) {
      writer.uint32(8).uint32(message.sensorId);
    }
    if (message.displayName !== "") {
      writer.uint32(18).string(message.displayName);
    }
    for (const v of message.layers) {
      Layer.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetSensorDetailsResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSensorDetailsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.sensorId = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.displayName = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.layers.push(Layer.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSensorDetailsResponse {
    return {
      sensorId: isSet(object.sensorId) ? globalThis.Number(object.sensorId) : 0,
      displayName: isSet(object.displayName) ? globalThis.String(object.displayName) : "",
      layers: globalThis.Array.isArray(object?.layers) ? object.layers.map((e: any) => Layer.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetSensorDetailsResponse): unknown {
    const obj: any = {};
    if (message.sensorId !== 0) {
      obj.sensorId = Math.round(message.sensorId);
    }
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.layers?.length) {
      obj.layers = message.layers.map((e) => Layer.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetSensorDetailsResponse>, I>>(base?: I): GetSensorDetailsResponse {
    return GetSensorDetailsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetSensorDetailsResponse>, I>>(object: I): GetSensorDetailsResponse {
    const message = createBaseGetSensorDetailsResponse();
    message.sensorId = object.sensorId ?? 0;
    message.displayName = object.displayName ?? "";
    message.layers = object.layers?.map((e) => Layer.fromPartial(e)) || [];
    return message;
  },
};

function createBaseLayer(): Layer {
  return { id: 0, name: "", bindings: [] };
}

export const Layer = {
  encode(message: Layer, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    for (const v of message.bindings) {
      BehaviorBinding.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Layer {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLayer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.bindings.push(BehaviorBinding.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Layer {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      bindings: globalThis.Array.isArray(object?.bindings)
        ? object.bindings.map((e: any) => BehaviorBinding.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Layer): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.bindings?.length) {
      obj.bindings = message.bindings.map((e) => BehaviorBinding.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Layer>, I>>(base?: I): Layer {
    return Layer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Layer>, I>>(object: I): Layer {
    const message = createBaseLayer();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.bindings = object.bindings?.map((e) => BehaviorBinding.fromPartial(e)) || [];
    return message;
  },
};

function createBaseBehaviorBinding(): BehaviorBinding {
  return { behaviorId: 0, param1: 0, param2: 0 };
}

export const BehaviorBinding = {
  encode(message: BehaviorBinding, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.behaviorId !== 0) {
      writer.uint32(8).sint32(message.behaviorId);
    }
    if (message.param1 !== 0) {
      writer.uint32(16).uint32(message.param1);
    }
    if (message.param2 !== 0) {
      writer.uint32(24).uint32(message.param2);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): BehaviorBinding {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBehaviorBinding();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.behaviorId = reader.sint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.param1 = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.param2 = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BehaviorBinding {
    return {
      behaviorId: isSet(object.behaviorId) ? globalThis.Number(object.behaviorId) : 0,
      param1: isSet(object.param1) ? globalThis.Number(object.param1) : 0,
      param2: isSet(object.param2) ? globalThis.Number(object.param2) : 0,
    };
  },

  toJSON(message: BehaviorBinding): unknown {
    const obj: any = {};
    if (message.behaviorId !== 0) {
      obj.behaviorId = Math.round(message.behaviorId);
    }
    if (message.param1 !== 0) {
      obj.param1 = Math.round(message.param1);
    }
    if (message.param2 !== 0) {
      obj.param2 = Math.round(message.param2);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BehaviorBinding>, I>>(base?: I): BehaviorBinding {
    return BehaviorBinding.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BehaviorBinding>, I>>(object: I): BehaviorBinding {
    const message = createBaseBehaviorBinding();
    message.behaviorId = object.behaviorId ?? 0;
    message.param1 = object.param1 ?? 0;
    message.param2 = object.param2 ?? 0;
    return message;
  },
};

function createBaseNotification(): Notification {
  return { unsavedChangesStatusChanged: undefined };
}

export const Notification = {
  encode(message: Notification, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.unsavedChangesStatusChanged !== undefined) {
      writer.uint32(8).bool(message.unsavedChangesStatusChanged);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Notification {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.unsavedChangesStatusChanged = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Notification {
    return {
      unsavedChangesStatusChanged: isSet(object.unsavedChangesStatusChanged)
        ? globalThis.Boolean(object.unsavedChangesStatusChanged)
        : undefined,
    };
  },

  toJSON(message: Notification): unknown {
    const obj: any = {};
    if (message.unsavedChangesStatusChanged !== undefined) {
      obj.unsavedChangesStatusChanged = message.unsavedChangesStatusChanged;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Notification>, I>>(base?: I): Notification {
    return Notification.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Notification>, I>>(object: I): Notification {
    const message = createBaseNotification();
    message.unsavedChangesStatusChanged = object.unsavedChangesStatusChanged ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
