// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v7.35.0
// source: studio.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { Request as Request2, Response as Response9 } from "./behaviors";
import { Notification as Notification14, Request as Request1, Response as Response8 } from "./core";
import { Notification as Notification15, Request as Request3, Response as Response10 } from "./keymap";
import { Notification as Notification17, Request as Request5, Response as Response12 } from "./macros";
import { Response as Response7 } from "./meta";
import { Notification as Notification16, Request as Request4, Response as Response11 } from "./sensors";
import { Notification as Notification18, Request as Request6, Response as Response13 } from "./touchpad";

export const protobufPackage = "zmk.studio";

/** Requests */

export interface Request {
  requestId: number;
  core?: Request1 | undefined;
  behaviors?: Request2 | undefined;
  keymap?: Request3 | undefined;
  sensors?: Request4 | undefined;
  macros?: Request5 | undefined;
  touchpad?: Request6 | undefined;
}

export interface Response {
  requestResponse?: RequestResponse | undefined;
  notification?: Notification | undefined;
}

export interface RequestResponse {
  requestId: number;
  meta?: Response7 | undefined;
  core?: Response8 | undefined;
  behaviors?: Response9 | undefined;
  keymap?: Response10 | undefined;
  sensors?: Response11 | undefined;
  macros?: Response12 | undefined;
  touchpad?: Response13 | undefined;
}

export interface Notification {
  core?: Notification14 | undefined;
  keymap?: Notification15 | undefined;
  sensors?: Notification16 | undefined;
  macros?: Notification17 | undefined;
  touchpad?: Notification18 | undefined;
}

function createBaseRequest(): Request {
  return {
    requestId: 0,
    core: undefined,
    behaviors: undefined,
    keymap: undefined,
    sensors: undefined,
    macros: undefined,
    touchpad: undefined,
  };
}

export const Request = {
  encode(message: Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.requestId !== 0) {
      writer.uint32(8).uint32(message.requestId);
    }
    if (message.core !== undefined) {
      Request1.encode(message.core, writer.uint32(26).fork()).ldelim();
    }
    if (message.behaviors !== undefined) {
      Request2.encode(message.behaviors, writer.uint32(34).fork()).ldelim();
    }
    if (message.keymap !== undefined) {
      Request3.encode(message.keymap, writer.uint32(42).fork()).ldelim();
    }
    if (message.sensors !== undefined) {
      Request4.encode(message.sensors, writer.uint32(50).fork()).ldelim();
    }
    if (message.macros !== undefined) {
      Request5.encode(message.macros, writer.uint32(58).fork()).ldelim();
    }
    if (message.touchpad !== undefined) {
      Request6.encode(message.touchpad, writer.uint32(66).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.requestId = reader.uint32();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.core = Request1.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.behaviors = Request2.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.keymap = Request3.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.sensors = Request4.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.macros = Request5.decode(reader, reader.uint32());
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.touchpad = Request6.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Request {
    return {
      requestId: isSet(object.requestId) ? globalThis.Number(object.requestId) : 0,
      core: isSet(object.core) ? Request1.fromJSON(object.core) : undefined,
      behaviors: isSet(object.behaviors) ? Request2.fromJSON(object.behaviors) : undefined,
      keymap: isSet(object.keymap) ? Request3.fromJSON(object.keymap) : undefined,
      sensors: isSet(object.sensors) ? Request4.fromJSON(object.sensors) : undefined,
      macros: isSet(object.macros) ? Request5.fromJSON(object.macros) : undefined,
      touchpad: isSet(object.touchpad) ? Request6.fromJSON(object.touchpad) : undefined,
    };
  },

  toJSON(message: Request): unknown {
    const obj: any = {};
    if (message.requestId !== 0) {
      obj.requestId = Math.round(message.requestId);
    }
    if (message.core !== undefined) {
      obj.core = Request1.toJSON(message.core);
    }
    if (message.behaviors !== undefined) {
      obj.behaviors = Request2.toJSON(message.behaviors);
    }
    if (message.keymap !== undefined) {
      obj.keymap = Request3.toJSON(message.keymap);
    }
    if (message.sensors !== undefined) {
      obj.sensors = Request4.toJSON(message.sensors);
    }
    if (message.macros !== undefined) {
      obj.macros = Request5.toJSON(message.macros);
    }
    if (message.touchpad !== undefined) {
      obj.touchpad = Request6.toJSON(message.touchpad);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Request>, I>>(base?: I): Request {
    return Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request>, I>>(object: I): Request {
    const message = createBaseRequest();
    message.requestId = object.requestId ?? 0;
    message.core = (object.core !== undefined && object.core !== null) ? Request1.fromPartial(object.core) : undefined;
    message.behaviors = (object.behaviors !== undefined && object.behaviors !== null)
      ? Request2.fromPartial(object.behaviors)
      : undefined;
    message.keymap = (object.keymap !== undefined && object.keymap !== null)
      ? Request3.fromPartial(object.keymap)
      : undefined;
    message.sensors = (object.sensors !== undefined && object.sensors !== null)
      ? Request4.fromPartial(object.sensors)
      : undefined;
    message.macros = (object.macros !== undefined && object.macros !== null)
      ? Request5.fromPartial(object.macros)
      : undefined;
    message.touchpad = (object.touchpad !== undefined && object.touchpad !== null)
      ? Request6.fromPartial(object.touchpad)
      : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return { requestResponse: undefined, notification: undefined };
}

export const Response = {
  encode(message: Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.requestResponse !== undefined) {
      RequestResponse.encode(message.requestResponse, writer.uint32(10).fork()).ldelim();
    }
    if (message.notification !== undefined) {
      Notification.encode(message.notification, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.requestResponse = RequestResponse.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.notification = Notification.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return {
      requestResponse: isSet(object.requestResponse) ? RequestResponse.fromJSON(object.requestResponse) : undefined,
      notification: isSet(object.notification) ? Notification.fromJSON(object.notification) : undefined,
    };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.requestResponse !== undefined) {
      obj.requestResponse = RequestResponse.toJSON(message.requestResponse);
    }
    if (message.notification !== undefined) {
      obj.notification = Notification.toJSON(message.notification);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Response>, I>>(base?: I): Response {
    return Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Response>, I>>(object: I): Response {
    const message = createBaseResponse();
    message.requestResponse = (object.requestResponse !== undefined && object.requestResponse !== null)
      ? RequestResponse.fromPartial(object.requestResponse)
      : undefined;
    message.notification = (object.notification !== undefined && object.notification !== null)
      ? Notification.fromPartial(object.notification)
      : undefined;
    return message;
  },
};

function createBaseRequestResponse(): RequestResponse {
  return {
    requestId: 0,
    meta: undefined,
    core: undefined,
    behaviors: undefined,
    keymap: undefined,
    sensors: undefined,
    macros: undefined,
    touchpad: undefined,
  };
}

export const RequestResponse = {
  encode(message: RequestResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.requestId !== 0) {
      writer.uint32(8).uint32(message.requestId);
    }
    if (message.meta !== undefined) {
      Response7.encode(message.meta, writer.uint32(18).fork()).ldelim();
    }
    if (message.core !== undefined) {
      Response8.encode(message.core, writer.uint32(26).fork()).ldelim();
    }
    if (message.behaviors !== undefined) {
      Response9.encode(message.behaviors, writer.uint32(34).fork()).ldelim();
    }
    if (message.keymap !== undefined) {
      Response10.encode(message.keymap, writer.uint32(42).fork()).ldelim();
    }
    if (message.sensors !== undefined) {
      Response11.encode(message.sensors, writer.uint32(50).fork()).ldelim();
    }
    if (message.macros !== undefined) {
      Response12.encode(message.macros, writer.uint32(58).fork()).ldelim();
    }
    if (message.touchpad !== undefined) {
      Response13.encode(message.touchpad, writer.uint32(66).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RequestResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.requestId = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.meta = Response7.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.core = Response8.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.behaviors = Response9.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.keymap = Response10.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.sensors = Response11.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.macros = Response12.decode(reader, reader.uint32());
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.touchpad = Response13.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestResponse {
    return {
      requestId: isSet(object.requestId) ? globalThis.Number(object.requestId) : 0,
      meta: isSet(object.meta) ? Response7.fromJSON(object.meta) : undefined,
      core: isSet(object.core) ? Response8.fromJSON(object.core) : undefined,
      behaviors: isSet(object.behaviors) ? Response9.fromJSON(object.behaviors) : undefined,
      keymap: isSet(object.keymap) ? Response10.fromJSON(object.keymap) : undefined,
      sensors: isSet(object.sensors) ? Response11.fromJSON(object.sensors) : undefined,
      macros: isSet(object.macros) ? Response12.fromJSON(object.macros) : undefined,
      touchpad: isSet(object.touchpad) ? Response13.fromJSON(object.touchpad) : undefined,
    };
  },

  toJSON(message: RequestResponse): unknown {
    const obj: any = {};
    if (message.requestId !== 0) {
      obj.requestId = Math.round(message.requestId);
    }
    if (message.meta !== undefined) {
      obj.meta = Response7.toJSON(message.meta);
    }
    if (message.core !== undefined) {
      obj.core = Response8.toJSON(message.core);
    }
    if (message.behaviors !== undefined) {
      obj.behaviors = Response9.toJSON(message.behaviors);
    }
    if (message.keymap !== undefined) {
      obj.keymap = Response10.toJSON(message.keymap);
    }
    if (message.sensors !== undefined) {
      obj.sensors = Response11.toJSON(message.sensors);
    }
    if (message.macros !== undefined) {
      obj.macros = Response12.toJSON(message.macros);
    }
    if (message.touchpad !== undefined) {
      obj.touchpad = Response13.toJSON(message.touchpad);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestResponse>, I>>(base?: I): RequestResponse {
    return RequestResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestResponse>, I>>(object: I): RequestResponse {
    const message = createBaseRequestResponse();
    message.requestId = object.requestId ?? 0;
    message.meta = (object.meta !== undefined && object.meta !== null) ? Response7.fromPartial(object.meta) : undefined;
    message.core = (object.core !== undefined && object.core !== null) ? Response8.fromPartial(object.core) : undefined;
    message.behaviors = (object.behaviors !== undefined && object.behaviors !== null)
      ? Response9.fromPartial(object.behaviors)
      : undefined;
    message.keymap = (object.keymap !== undefined && object.keymap !== null)
      ? Response10.fromPartial(object.keymap)
      : undefined;
    message.sensors = (object.sensors !== undefined && object.sensors !== null)
      ? Response11.fromPartial(object.sensors)
      : undefined;
    message.macros = (object.macros !== undefined && object.macros !== null)
      ? Response12.fromPartial(object.macros)
      : undefined;
    message.touchpad = (object.touchpad !== undefined && object.touchpad !== null)
      ? Response13.fromPartial(object.touchpad)
      : undefined;
    return message;
  },
};

function createBaseNotification(): Notification {
  return { core: undefined, keymap: undefined, sensors: undefined, macros: undefined, touchpad: undefined };
}

export const Notification = {
  encode(message: Notification, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.core !== undefined) {
      Notification14.encode(message.core, writer.uint32(18).fork()).ldelim();
    }
    if (message.keymap !== undefined) {
      Notification15.encode(message.keymap, writer.uint32(42).fork()).ldelim();
    }
    if (message.sensors !== undefined) {
      Notification16.encode(message.sensors, writer.uint32(50).fork()).ldelim();
    }
    if (message.macros !== undefined) {
      Notification17.encode(message.macros, writer.uint32(58).fork()).ldelim();
    }
    if (message.touchpad !== undefined) {
      Notification18.encode(message.touchpad, writer.uint32(66).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Notification {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2:
          if (tag !== 18) {
            break;
          }

          message.core = Notification14.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.keymap = Notification15.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.sensors = Notification16.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.macros = Notification17.decode(reader, reader.uint32());
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.touchpad = Notification18.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Notification {
    return {
      core: isSet(object.core) ? Notification14.fromJSON(object.core) : undefined,
      keymap: isSet(object.keymap) ? Notification15.fromJSON(object.keymap) : undefined,
      sensors: isSet(object.sensors) ? Notification16.fromJSON(object.sensors) : undefined,
      macros: isSet(object.macros) ? Notification17.fromJSON(object.macros) : undefined,
      touchpad: isSet(object.touchpad) ? Notification18.fromJSON(object.touchpad) : undefined,
    };
  },

  toJSON(message: Notification): unknown {
    const obj: any = {};
    if (message.core !== undefined) {
      obj.core = Notification14.toJSON(message.core);
    }
    if (message.keymap !== undefined) {
      obj.keymap = Notification15.toJSON(message.keymap);
    }
    if (message.sensors !== undefined) {
      obj.sensors = Notification16.toJSON(message.sensors);
    }
    if (message.macros !== undefined) {
      obj.macros = Notification17.toJSON(message.macros);
    }
    if (message.touchpad !== undefined) {
      obj.touchpad = Notification18.toJSON(message.touchpad);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Notification>, I>>(base?: I): Notification {
    return Notification.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Notification>, I>>(object: I): Notification {
    const message = createBaseNotification();
    message.core = (object.core !== undefined && object.core !== null)
      ? Notification14.fromPartial(object.core)
      : undefined;
    message.keymap = (object.keymap !== undefined && object.keymap !== null)
      ? Notification15.fromPartial(object.keymap)
      : undefined;
    message.sensors = (object.sensors !== undefined && object.sensors !== null)
      ? Notification16.fromPartial(object.sensors)
      : undefined;
    message.macros = (object.macros !== undefined && object.macros !== null)
      ? Notification17.fromPartial(object.macros)
      : undefined;
    message.touchpad = (object.touchpad !== undefined && object.touchpad !== null)
      ? Notification18.fromPartial(object.touchpad)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
