// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v7.35.0
// source: touchpad.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { BehaviorBinding } from "./keymap";

export const protobufPackage = "zmk.touchpad";

export enum Mode {
  MODE_UNSPECIFIED = 0,
  MODE_GESTURE = 1,
  MODE_MOUSE_SIMULATION = 2,
  UNRECOGNIZED = -1,
}

export function modeFromJSON(object: any): Mode {
  switch (object) {
    case 0:
    case "MODE_UNSPECIFIED":
      return Mode.MODE_UNSPECIFIED;
    case 1:
    case "MODE_GESTURE":
      return Mode.MODE_GESTURE;
    case 2:
    case "MODE_MOUSE_SIMULATION":
      return Mode.MODE_MOUSE_SIMULATION;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Mode.UNRECOGNIZED;
  }
}

export function modeToJSON(object: Mode): string {
  switch (object) {
    case Mode.MODE_UNSPECIFIED:
      return "MODE_UNSPECIFIED";
    case Mode.MODE_GESTURE:
      return "MODE_GESTURE";
    case Mode.MODE_MOUSE_SIMULATION:
      return "MODE_MOUSE_SIMULATION";
    case Mode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ModeResult {
  MODE_OK = 0,
  MODE_INVALID_LAYER = 1,
  UNRECOGNIZED = -1,
}

export function modeResultFromJSON(object: any): ModeResult {
  switch (object) {
    case 0:
    case "MODE_OK":
      return ModeResult.MODE_OK;
    case 1:
    case "MODE_INVALID_LAYER":
      return ModeResult.MODE_INVALID_LAYER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ModeResult.UNRECOGNIZED;
  }
}

export function modeResultToJSON(object: ModeResult): string {
  switch (object) {
    case ModeResult.MODE_OK:
      return "MODE_OK";
    case ModeResult.MODE_INVALID_LAYER:
      return "MODE_INVALID_LAYER";
    case ModeResult.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum BindResult {
  BIND_OK = 0,
  BIND_INVALID_LAYER = 1,
  BIND_INVALID_BEHAVIOR = 2,
  UNRECOGNIZED = -1,
}

export function bindResultFromJSON(object: any): BindResult {
  switch (object) {
    case 0:
    case "BIND_OK":
      return BindResult.BIND_OK;
    case 1:
    case "BIND_INVALID_LAYER":
      return BindResult.BIND_INVALID_LAYER;
    case 2:
    case "BIND_INVALID_BEHAVIOR":
      return BindResult.BIND_INVALID_BEHAVIOR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return BindResult.UNRECOGNIZED;
  }
}

export function bindResultToJSON(object: BindResult): string {
  switch (object) {
    case BindResult.BIND_OK:
      return "BIND_OK";
    case BindResult.BIND_INVALID_LAYER:
      return "BIND_INVALID_LAYER";
    case BindResult.BIND_INVALID_BEHAVIOR:
      return "BIND_INVALID_BEHAVIOR";
    case BindResult.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum SaveResult {
  SAVE_OK = 0,
  SAVE_ERR = 1,
  UNRECOGNIZED = -1,
}

export function saveResultFromJSON(object: any): SaveResult {
  switch (object) {
    case 0:
    case "SAVE_OK":
      return SaveResult.SAVE_OK;
    case 1:
    case "SAVE_ERR":
      return SaveResult.SAVE_ERR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SaveResult.UNRECOGNIZED;
  }
}

export function saveResultToJSON(object: SaveResult): string {
  switch (object) {
    case SaveResult.SAVE_OK:
      return "SAVE_OK";
    case SaveResult.SAVE_ERR:
      return "SAVE_ERR";
    case SaveResult.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface TouchpadConfig {
  layers: Layer[];
}

export interface Layer {
  id: number;
  name: string;
  mode: Mode;
  bindings: BehaviorBinding[];
}

export interface Request {
  getConfig?: GetTouchpadConfigRequest | undefined;
  setMode?: SetTouchpadModeRequest | undefined;
  setLayerBindings?: SetLayerBindingsRequest | undefined;
  checkUnsavedChanges?: CheckUnsavedChangesRequest | undefined;
  saveChanges?: SaveChangesRequest | undefined;
  discardChanges?: DiscardChangesRequest | undefined;
}

export interface GetTouchpadConfigRequest {
}

export interface SetTouchpadModeRequest {
  layerId: number;
  mode: Mode;
}

export interface SetLayerBindingsRequest {
  layerId: number;
  bindings: BehaviorBinding[];
}

export interface CheckUnsavedChangesRequest {
}

export interface SaveChangesRequest {
}

export interface DiscardChangesRequest {
}

export interface Response {
  getConfig?: TouchpadConfig | undefined;
  setMode?: SetTouchpadModeResponse | undefined;
  setLayerBindings?: SetLayerBindingsResponse | undefined;
  checkUnsavedChanges?: boolean | undefined;
  saveChanges?: SaveChangesResponse | undefined;
  discardChanges?: boolean | undefined;
}

export interface SetTouchpadModeResponse {
  result: ModeResult;
}

export interface SetLayerBindingsResponse {
  result: BindResult;
}

export interface SaveChangesResponse {
  ok?: boolean | undefined;
  err?: SaveResult | undefined;
}

export interface DiscardChangesResponse {
  success: boolean;
}

export interface Notification {
  unsavedChangesStatusChanged?: boolean | undefined;
}

function createBaseTouchpadConfig(): TouchpadConfig {
  return { layers: [] };
}

export const TouchpadConfig = {
  encode(message: TouchpadConfig, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.layers) {
      Layer.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TouchpadConfig {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTouchpadConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.layers.push(Layer.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TouchpadConfig {
    return { layers: globalThis.Array.isArray(object?.layers) ? object.layers.map((e: any) => Layer.fromJSON(e)) : [] };
  },

  toJSON(message: TouchpadConfig): unknown {
    const obj: any = {};
    if (message.layers?.length) {
      obj.layers = message.layers.map((e) => Layer.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TouchpadConfig>, I>>(base?: I): TouchpadConfig {
    return TouchpadConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TouchpadConfig>, I>>(object: I): TouchpadConfig {
    const message = createBaseTouchpadConfig();
    message.layers = object.layers?.map((e) => Layer.fromPartial(e)) || [];
    return message;
  },
};

function createBaseLayer(): Layer {
  return { id: 0, name: "", mode: 0, bindings: [] };
}

export const Layer = {
  encode(message: Layer, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.mode !== 0) {
      writer.uint32(24).int32(message.mode);
    }
    for (const v of message.bindings) {
      BehaviorBinding.encode(v!, writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Layer {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLayer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.mode = reader.int32() as any;
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.bindings.push(BehaviorBinding.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Layer {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      mode: isSet(object.mode) ? modeFromJSON(object.mode) : 0,
      bindings: globalThis.Array.isArray(object?.bindings)
        ? object.bindings.map((e: any) => BehaviorBinding.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Layer): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.mode !== 0) {
      obj.mode = modeToJSON(message.mode);
    }
    if (message.bindings?.length) {
      obj.bindings = message.bindings.map((e) => BehaviorBinding.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Layer>, I>>(base?: I): Layer {
    return Layer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Layer>, I>>(object: I): Layer {
    const message = createBaseLayer();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.mode = object.mode ?? 0;
    message.bindings = object.bindings?.map((e) => BehaviorBinding.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRequest(): Request {
  return {
    getConfig: undefined,
    setMode: undefined,
    setLayerBindings: undefined,
    checkUnsavedChanges: undefined,
    saveChanges: undefined,
    discardChanges: undefined,
  };
}

export const Request = {
  encode(message: Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.getConfig !== undefined) {
      GetTouchpadConfigRequest.encode(message.getConfig, writer.uint32(10).fork()).ldelim();
    }
    if (message.setMode !== undefined) {
      SetTouchpadModeRequest.encode(message.setMode, writer.uint32(18).fork()).ldelim();
    }
    if (message.setLayerBindings !== undefined) {
      SetLayerBindingsRequest.encode(message.setLayerBindings, writer.uint32(26).fork()).ldelim();
    }
    if (message.checkUnsavedChanges !== undefined) {
      CheckUnsavedChangesRequest.encode(message.checkUnsavedChanges, writer.uint32(34).fork()).ldelim();
    }
    if (message.saveChanges !== undefined) {
      SaveChangesRequest.encode(message.saveChanges, writer.uint32(42).fork()).ldelim();
    }
    if (message.discardChanges !== undefined) {
      DiscardChangesRequest.encode(message.discardChanges, writer.uint32(50).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.getConfig = GetTouchpadConfigRequest.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.setMode = SetTouchpadModeRequest.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.setLayerBindings = SetLayerBindingsRequest.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.checkUnsavedChanges = CheckUnsavedChangesRequest.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.saveChanges = SaveChangesRequest.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.discardChanges = DiscardChangesRequest.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Request {
    return {
      getConfig: isSet(object.getConfig) ? GetTouchpadConfigRequest.fromJSON(object.getConfig) : undefined,
      setMode: isSet(object.setMode) ? SetTouchpadModeRequest.fromJSON(object.setMode) : undefined,
      setLayerBindings: isSet(object.setLayerBindings)
        ? SetLayerBindingsRequest.fromJSON(object.setLayerBindings)
        : undefined,
      checkUnsavedChanges: isSet(object.checkUnsavedChanges)
        ? CheckUnsavedChangesRequest.fromJSON(object.checkUnsavedChanges)
        : undefined,
      saveChanges: isSet(object.saveChanges) ? SaveChangesRequest.fromJSON(object.saveChanges) : undefined,
      discardChanges: isSet(object.discardChanges) ? DiscardChangesRequest.fromJSON(object.discardChanges) : undefined,
    };
  },

  toJSON(message: Request): unknown {
    const obj: any = {};
    if (message.getConfig !== undefined) {
      obj.getConfig = GetTouchpadConfigRequest.toJSON(message.getConfig);
    }
    if (message.setMode !== undefined) {
      obj.setMode = SetTouchpadModeRequest.toJSON(message.setMode);
    }
    if (message.setLayerBindings !== undefined) {
      obj.setLayerBindings = SetLayerBindingsRequest.toJSON(message.setLayerBindings);
    }
    if (message.checkUnsavedChanges !== undefined) {
      obj.checkUnsavedChanges = CheckUnsavedChangesRequest.toJSON(message.checkUnsavedChanges);
    }
    if (message.saveChanges !== undefined) {
      obj.saveChanges = SaveChangesRequest.toJSON(message.saveChanges);
    }
    if (message.discardChanges !== undefined) {
      obj.discardChanges = DiscardChangesRequest.toJSON(message.discardChanges);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Request>, I>>(base?: I): Request {
    return Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request>, I>>(object: I): Request {
    const message = createBaseRequest();
    message.getConfig = (object.getConfig !== undefined && object.getConfig !== null)
      ? GetTouchpadConfigRequest.fromPartial(object.getConfig)
      : undefined;
    message.setMode = (object.setMode !== undefined && object.setMode !== null)
      ? SetTouchpadModeRequest.fromPartial(object.setMode)
      : undefined;
    message.setLayerBindings = (object.setLayerBindings !== undefined && object.setLayerBindings !== null)
      ? SetLayerBindingsRequest.fromPartial(object.setLayerBindings)
      : undefined;
    message.checkUnsavedChanges = (object.checkUnsavedChanges !== undefined && object.checkUnsavedChanges !== null)
      ? CheckUnsavedChangesRequest.fromPartial(object.checkUnsavedChanges)
      : undefined;
    message.saveChanges = (object.saveChanges !== undefined && object.saveChanges !== null)
      ? SaveChangesRequest.fromPartial(object.saveChanges)
      : undefined;
    message.discardChanges = (object.discardChanges !== undefined && object.discardChanges !== null)
      ? DiscardChangesRequest.fromPartial(object.discardChanges)
      : undefined;
    return message;
  },
};

function createBaseGetTouchpadConfigRequest(): GetTouchpadConfigRequest {
  return {};
}

export const GetTouchpadConfigRequest = {
  encode(_: GetTouchpadConfigRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetTouchpadConfigRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTouchpadConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetTouchpadConfigRequest {
    return {};
  },

  toJSON(_: GetTouchpadConfigRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTouchpadConfigRequest>, I>>(base?: I): GetTouchpadConfigRequest {
    return GetTouchpadConfigRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTouchpadConfigRequest>, I>>(_: I): GetTouchpadConfigRequest {
    const message = createBaseGetTouchpadConfigRequest();
    return message;
  },
};

function createBaseSetTouchpadModeRequest(): SetTouchpadModeRequest {
  return { layerId: 0, mode: 0 };
}

export const SetTouchpadModeRequest = {
  encode(message: SetTouchpadModeRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.layerId !== 0) {
      writer.uint32(8).uint32(message.layerId);
    }
    if (message.mode !== 0) {
      writer.uint32(16).int32(message.mode);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetTouchpadModeRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetTouchpadModeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.layerId = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.mode = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetTouchpadModeRequest {
    return {
      layerId: isSet(object.layerId) ? globalThis.Number(object.layerId) : 0,
      mode: isSet(object.mode) ? modeFromJSON(object.mode) : 0,
    };
  },

  toJSON(message: SetTouchpadModeRequest): unknown {
    const obj: any = {};
    if (message.layerId !== 0) {
      obj.layerId = Math.round(message.layerId);
    }
    if (message.mode !== 0) {
      obj.mode = modeToJSON(message.mode);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetTouchpadModeRequest>, I>>(base?: I): SetTouchpadModeRequest {
    return SetTouchpadModeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetTouchpadModeRequest>, I>>(object: I): SetTouchpadModeRequest {
    const message = createBaseSetTouchpadModeRequest();
    message.layerId = object.layerId ?? 0;
    message.mode = object.mode ?? 0;
    return message;
  },
};

function createBaseSetLayerBindingsRequest(): SetLayerBindingsRequest {
  return { layerId: 0, bindings: [] };
}

export const SetLayerBindingsRequest = {
  encode(message: SetLayerBindingsRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.layerId !== 0) {
      writer.uint32(8).uint32(message.layerId);
    }
    for (const v of message.bindings) {
      BehaviorBinding.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetLayerBindingsRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetLayerBindingsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.layerId = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.bindings.push(BehaviorBinding.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetLayerBindingsRequest {
    return {
      layerId: isSet(object.layerId) ? globalThis.Number(object.layerId) : 0,
      bindings: globalThis.Array.isArray(object?.bindings)
        ? object.bindings.map((e: any) => BehaviorBinding.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SetLayerBindingsRequest): unknown {
    const obj: any = {};
    if (message.layerId !== 0) {
      obj.layerId = Math.round(message.layerId);
    }
    if (message.bindings?.length) {
      obj.bindings = message.bindings.map((e) => BehaviorBinding.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetLayerBindingsRequest>, I>>(base?: I): SetLayerBindingsRequest {
    return SetLayerBindingsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetLayerBindingsRequest>, I>>(object: I): SetLayerBindingsRequest {
    const message = createBaseSetLayerBindingsRequest();
    message.layerId = object.layerId ?? 0;
    message.bindings = object.bindings?.map((e) => BehaviorBinding.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCheckUnsavedChangesRequest(): CheckUnsavedChangesRequest {
  return {};
}

export const CheckUnsavedChangesRequest = {
  encode(_: CheckUnsavedChangesRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CheckUnsavedChangesRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckUnsavedChangesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CheckUnsavedChangesRequest {
    return {};
  },

  toJSON(_: CheckUnsavedChangesRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckUnsavedChangesRequest>, I>>(base?: I): CheckUnsavedChangesRequest {
    return CheckUnsavedChangesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckUnsavedChangesRequest>, I>>(_: I): CheckUnsavedChangesRequest {
    const message = createBaseCheckUnsavedChangesRequest();
    return message;
  },
};

function createBaseSaveChangesRequest(): SaveChangesRequest {
  return {};
}

export const SaveChangesRequest = {
  encode(_: SaveChangesRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SaveChangesRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSaveChangesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SaveChangesRequest {
    return {};
  },

  toJSON(_: SaveChangesRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SaveChangesRequest>, I>>(base?: I): SaveChangesRequest {
    return SaveChangesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SaveChangesRequest>, I>>(_: I): SaveChangesRequest {
    const message = createBaseSaveChangesRequest();
    return message;
  },
};

function createBaseDiscardChangesRequest(): DiscardChangesRequest {
  return {};
}

export const DiscardChangesRequest = {
  encode(_: DiscardChangesRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DiscardChangesRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDiscardChangesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): DiscardChangesRequest {
    return {};
  },

  toJSON(_: DiscardChangesRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<DiscardChangesRequest>, I>>(base?: I): DiscardChangesRequest {
    return DiscardChangesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DiscardChangesRequest>, I>>(_: I): DiscardChangesRequest {
    const message = createBaseDiscardChangesRequest();
    return message;
  },
};

function createBaseResponse(): Response {
  return {
    getConfig: undefined,
    setMode: undefined,
    setLayerBindings: undefined,
    checkUnsavedChanges: undefined,
    saveChanges: undefined,
    discardChanges: undefined,
  };
}

export const Response = {
  encode(message: Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.getConfig !== undefined) {
      TouchpadConfig.encode(message.getConfig, writer.uint32(10).fork()).ldelim();
    }
    if (message.setMode !== undefined) {
      SetTouchpadModeResponse.encode(message.setMode, writer.uint32(18).fork()).ldelim();
    }
    if (message.setLayerBindings !== undefined) {
      SetLayerBindingsResponse.encode(message.setLayerBindings, writer.uint32(26).fork()).ldelim();
    }
    if (message.checkUnsavedChanges !== undefined) {
      writer.uint32(32).bool(message.checkUnsavedChanges);
    }
    if (message.saveChanges !== undefined) {
      SaveChangesResponse.encode(message.saveChanges, writer.uint32(42).fork()).ldelim();
    }
    if (message.discardChanges !== undefined) {
      writer.uint32(48).bool(message.discardChanges);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.getConfig = TouchpadConfig.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.setMode = SetTouchpadModeResponse.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.setLayerBindings = SetLayerBindingsResponse.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.checkUnsavedChanges = reader.bool();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.saveChanges = SaveChangesResponse.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.discardChanges = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return {
      getConfig: isSet(object.getConfig) ? TouchpadConfig.fromJSON(object.getConfig) : undefined,
      setMode: isSet(object.setMode) ? SetTouchpadModeResponse.fromJSON(object.setMode) : undefined,
      setLayerBindings: isSet(object.setLayerBindings)
        ? SetLayerBindingsResponse.fromJSON(object.setLayerBindings)
        : undefined,
      checkUnsavedChanges: isSet(object.checkUnsavedChanges)
        ? globalThis.Boolean(object.checkUnsavedChanges)
        : undefined,
      saveChanges: isSet(object.saveChanges) ? SaveChangesResponse.fromJSON(object.saveChanges) : undefined,
      discardChanges: isSet(object.discardChanges) ? globalThis.Boolean(object.discardChanges) : undefined,
    };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.getConfig !== undefined) {
      obj.getConfig = TouchpadConfig.toJSON(message.getConfig);
    }
    if (message.setMode !== undefined) {
      obj.setMode = SetTouchpadModeResponse.toJSON(message.setMode);
    }
    if (message.setLayerBindings !== undefined) {
      obj.setLayerBindings = SetLayerBindingsResponse.toJSON(message.setLayerBindings);
    }
    if (message.checkUnsavedChanges !== undefined) {
      obj.checkUnsavedChanges = message.checkUnsavedChanges;
    }
    if (message.saveChanges !== undefined) {
      obj.saveChanges = SaveChangesResponse.toJSON(message.saveChanges);
    }
    if (message.discardChanges !== undefined) {
      obj.discardChanges = message.discardChanges;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Response>, I>>(base?: I): Response {
    return Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Response>, I>>(object: I): Response {
    const message = createBaseResponse();
    message.getConfig = (object.getConfig !== undefined && object.getConfig !== null)
      ? TouchpadConfig.fromPartial(object.getConfig)
      : undefined;
    message.setMode = (object.setMode !== undefined && object.setMode !== null)
      ? SetTouchpadModeResponse.fromPartial(object.setMode)
      : undefined;
    message.setLayerBindings = (object.setLayerBindings !== undefined && object.setLayerBindings !== null)
      ? SetLayerBindingsResponse.fromPartial(object.setLayerBindings)
      : undefined;
    message.checkUnsavedChanges = object.checkUnsavedChanges ?? undefined;
    message.saveChanges = (object.saveChanges !== undefined && object.saveChanges !== null)
      ? SaveChangesResponse.fromPartial(object.saveChanges)
      : undefined;
    message.discardChanges = object.discardChanges ?? undefined;
    return message;
  },
};

function createBaseSetTouchpadModeResponse(): SetTouchpadModeResponse {
  return { result: 0 };
}

export const SetTouchpadModeResponse = {
  encode(message: SetTouchpadModeResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.result !== 0) {
      writer.uint32(8).int32(message.result);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetTouchpadModeResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetTouchpadModeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.result = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetTouchpadModeResponse {
    return { result: isSet(object.result) ? modeResultFromJSON(object.result) : 0 };
  },

  toJSON(message: SetTouchpadModeResponse): unknown {
    const obj: any = {};
    if (message.result !== 0) {
      obj.result = modeResultToJSON(message.result);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetTouchpadModeResponse>, I>>(base?: I): SetTouchpadModeResponse {
    return SetTouchpadModeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetTouchpadModeResponse>, I>>(object: I): SetTouchpadModeResponse {
    const message = createBaseSetTouchpadModeResponse();
    message.result = object.result ?? 0;
    return message;
  },
};

function createBaseSetLayerBindingsResponse(): SetLayerBindingsResponse {
  return { result: 0 };
}

export const SetLayerBindingsResponse = {
  encode(message: SetLayerBindingsResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.result !== 0) {
      writer.uint32(8).int32(message.result);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetLayerBindingsResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetLayerBindingsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.result = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetLayerBindingsResponse {
    return { result: isSet(object.result) ? bindResultFromJSON(object.result) : 0 };
  },

  toJSON(message: SetLayerBindingsResponse): unknown {
    const obj: any = {};
    if (message.result !== 0) {
      obj.result = bindResultToJSON(message.result);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetLayerBindingsResponse>, I>>(base?: I): SetLayerBindingsResponse {
    return SetLayerBindingsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetLayerBindingsResponse>, I>>(object: I): SetLayerBindingsResponse {
    const message = createBaseSetLayerBindingsResponse();
    message.result = object.result ?? 0;
    return message;
  },
};

function createBaseSaveChangesResponse(): SaveChangesResponse {
  return { ok: undefined, err: undefined };
}

export const SaveChangesResponse = {
  encode(message: SaveChangesResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ok !== undefined) {
      writer.uint32(8).bool(message.ok);
    }
    if (message.err !== undefined) {
      writer.uint32(16).int32(message.err);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SaveChangesResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSaveChangesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.ok = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.err = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SaveChangesResponse {
    return {
      ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : undefined,
      err: isSet(object.err) ? saveResultFromJSON(object.err) : undefined,
    };
  },

  toJSON(message: SaveChangesResponse): unknown {
    const obj: any = {};
    if (message.ok !== undefined) {
      obj.ok = message.ok;
    }
    if (message.err !== undefined) {
      obj.err = saveResultToJSON(message.err);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SaveChangesResponse>, I>>(base?: I): SaveChangesResponse {
    return SaveChangesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SaveChangesResponse>, I>>(object: I): SaveChangesResponse {
    const message = createBaseSaveChangesResponse();
    message.ok = object.ok ?? undefined;
    message.err = object.err ?? undefined;
    return message;
  },
};

function createBaseDiscardChangesResponse(): DiscardChangesResponse {
  return { success: false };
}

export const DiscardChangesResponse = {
  encode(message: DiscardChangesResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): DiscardChangesResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDiscardChangesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DiscardChangesResponse {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: DiscardChangesResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DiscardChangesResponse>, I>>(base?: I): DiscardChangesResponse {
    return DiscardChangesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DiscardChangesResponse>, I>>(object: I): DiscardChangesResponse {
    const message = createBaseDiscardChangesResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseNotification(): Notification {
  return { unsavedChangesStatusChanged: undefined };
}

export const Notification = {
  encode(message: Notification, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.unsavedChangesStatusChanged !== undefined) {
      writer.uint32(8).bool(message.unsavedChangesStatusChanged);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Notification {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.unsavedChangesStatusChanged = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Notification {
    return {
      unsavedChangesStatusChanged: isSet(object.unsavedChangesStatusChanged)
        ? globalThis.Boolean(object.unsavedChangesStatusChanged)
        : undefined,
    };
  },

  toJSON(message: Notification): unknown {
    const obj: any = {};
    if (message.unsavedChangesStatusChanged !== undefined) {
      obj.unsavedChangesStatusChanged = message.unsavedChangesStatusChanged;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Notification>, I>>(base?: I): Notification {
    return Notification.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Notification>, I>>(object: I): Notification {
    const message = createBaseNotification();
    message.unsavedChangesStatusChanged = object.unsavedChangesStatusChanged ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
